---
# tasks file for sbaerlocher.ovirt-guest-agent

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- block:
    - name: install EPEL repo
      yum:
        name: "{{ ovirt_repo_url }}"
        state: present
      register: result
      until: '"failed" not in result'
      retries: 5
      delay: 10
    - name: install Ovirt Guest Agent
      yum:
        name: "{{ item }}"
      with_items:
        - "{{ ovirt_package }}"
      notify:
        - enabled Ovirt Guest Agent
        - restart Ovirt Guest Agent
  when: ansible_distribution == "CentOS"
  tags:
    - packages

- block:
    - name: install Ovirt Guest Agent
      apt:
        name: "{{ item }}"
        force: yes
      with_items:
        - "{{ ovirt_package }}"
      notify:
        - enabled Ovirt Guest Agent
        - restart Ovirt Guest Agent
  when: ansible_distribution == "Debian"
  tags:
    - packages
