---
# handlers file for sbaerlocher.ovirt-guest-agent

- name: restart Ovirt Guest Agent
  service: name={{ ovirt_guest_agent_service_name }} state=restarted

- name: enabled Ovirt Guest Agent
  service: name={{ ovirt_guest_agent_service_name }} enabled=yes
